export enum KycStatus {
    PENDING = "PENDING",
    VERIFIED = 'VERIFIED',
    REJECTED = "REJECTED"
}

export enum UserRole {
    SUPER_ADMIN = 'SUPER_ADMIN',
    ADMIN = 'ADMIN',
    OPERATIONS_ADMIN = 'OPERATIONS_ADMIN',
    SUPPORT_ADMIN = 'SUPPORT_ADMIN',
    ANALYST = 'ANALYST',
    GUEST = 'GUEST',
    AGENT = 'AGENT',
    OWNER = 'OWNER',
    MANAGER = 'MANAGER',
}

export enum Gender {
    MALE = 'MALE',
    FEMALE = 'FEMALE',
    OTHER = 'OTHER',
}

export enum DisputeCategory {
    PROPERTY_MISMATCH = "PROPERTY_MISMATCH",
    CLEANLINESS = "CLEANLINESS",
    MISSING_AMENITIES = "MISSING_AMENITIES",
    UNAVAILABLE_CHECKIN = "UNAVAILABLE_CHECKIN",
    SAFETY_CONCERNS = "SAFETY_CONCERNS",
    GUEST_DAMAGE = "GUEST_DAMAGE",
    RULE_VIOLATION = "RULE_VIOLATION",
    UNAUTHORIZED_GUEST = "UNAUTHORIZED_GUEST",
    OVERSTAYING = "OVERSTAYING",
}

export enum DisputeStatus {
    OPEN = "OPEN",
    UNDER_REVIEW = "UNDER_REVIEW",
    AWAITING_EVIDENCE = "AWAITING_EVIDENCE",
    RESOLVED = "RESOLVED",
    CLOSED = "CLOSED",
}

export enum DisputeOutcome {
    NO_ACTION = "NO_ACTION",
    PARTIAL_REFUND = "PARTIAL_REFUND",
    PARTIAL_COMPENSATION = "PARTIAL_COMPENSATION",
    FULL_COMPENSATION = "FULL_COMPENSATION",
}
